### PR TITLE
Add cordova-plugin-file to README

### PR DESCRIPTION
**Pull request by Rakonda**

### CODE REVIEW

**Comment by vitaliy-bobrov** [comment]
@Rakonda I didn't add this plugin to readme, because file transfer plugins already has it as dependency

**Comment by almothafar** [comment]
@vitaliy-bobrov so I don't need to add `cordova-plugin-file` ?

I used a blog post that where I knew about this awesome plugin saying I have to install `cordova-plugin-file`

**Comment by vitaliy-bobrov** [comment]
you'll see that after file transfer plugin installation the file plugin will be installed as well in the console output

**Comment by vitaliy-bobrov** [comment]
@almothafar, could you give the link to blog post?)

**Pull request merged**
